# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Howdy
tagline:          'A website'
description:      'Code, teach, run, repeat'
url:              'www.kurtkaiser.us'
baseurl:          /

author:
  name:           'Kurt Kaiser'
  url:            rainyesplease

paginate:         5

# Custom vars
version:          2.1.0

github:
repo:           https://github.com/poole/hyde
